### PR TITLE
Clean up packaging and drop package.json.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@flatsiedatsie any interest in this?

**Comment by flatsiedatsie** [comment]
It seems the `requests` module is removed in this, while in other issues it seemed necessary to add it to the requirements?

**Comment by mrstegeman** [comment]
You're importing `requests` but never actually using it, making it unnecessary.

**Comment by flatsiedatsie** [comment]
Right as always :-)

**Pull request merged**
